leng_pass_min: 6
leng_email_max: 255
leng_name_max: 50
leng_address_max: 150
leng_phone_max: 30
check_remember: "1"
pic_size: 5
res_expired: 2
per_page_order_items: 10
size: "100x10"
per_page: 15
size_text_field: 10
